### ISSUE TITLE
Use component model `resource`s

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wasi-nn#47]
Once component model `resource`s are fully implemented, this specification should switch to using them for graphs, execution contexts, and possibly tensors (see https://github.com/WebAssembly/wasi-nn/issues/43).

**Comment by geekbeast** [comment]
Many of the execution context functions can be attached to graph once it is a resource. I'm not sure execution context makes sense as a resource since they shouldn't be shared (i.e they are tied to a specific instance of a graph so you will get into lifetime management issues). Doing this for large tensors could be make sense (i.e images) especially if being processed by a pipeline of components.
