### ISSUE TITLE
Add enum for tensor layout

### ISSUE THREAD

**Issue by oovm** [WebAssembly/wasi-nn#67]
Is it possible to add an interface to get the tensor layout (memory format) of tensor?

Such as `NCHW` or `NWHC`, I hope that incorrect arrangements can be determined and rejected in wasm
​

**Comment by oovm** [comment]
Sorry, I can't attend this meeting, I am not an English speaker, I use Google and chatgpt to translate the conversation, but I will pay attention to the meeting minutes.

**Comment by abrown** [comment]
No problem; I will relay this request in the meeting then.

**Comment by abrown** [comment]
@oovm, we discussed this at the last ML meeting ([here](https://github.com/bytecodealliance/meetings/pull/253)) and here is a summary of that discussion:
- the difference between NHWC, NCHW, etc. is specific to tensors that represent images
- wasi-nn is a system-level API and cannot possibly provide developer-friendly features for every specific ML use case
- if it were to provide something like this metadata, it might need to be more unstructured than an enum (e.g., key-value strings) _and_ be accessible from the graph resource, not at the tensor level
- some of those present have discussed adding unstructured metadata to graphs, so that may be an avenue to explore
- but, in the end, that additional information doesn't free the developer from knowing how to properly interface with the ML model they choose to do inference with; being able to extract some model metadata doesn't fully solve the problem of making this API easier to use

I believe there is plenty of room above the system API level for an ease-of-use wrapper library; there are the beginnings of this kind of thing over in [this repository](https://github.com/bytecodealliance/wasi-nn).
