### ISSUE TITLE
README.md does not say what WASI-nn is

### ISSUE THREAD

**Issue by prescod** [WebAssembly/wasi-nn#7]
The README.md does not say what WASI-nn is.

**Comment by abrown** [comment]
Yeah, that is a bit confusing. The general process for proposals to WASI is to fork the main repository, make changes, and eventually merge them back in. If we add any wasi-nn specific text to the README we will have to remove it before merging; since that will probably take quite some time, I don't see an issue with adding a small descriptive paragraph. Or are you looking for a more in-depth explanation? [This blog post](https://bytecodealliance.org/articles/using-wasi-nn-in-wasmtime) might give more details.

**Comment by prescod** [comment]
I agree that a small descriptive paragraph would be a good idea and you could link to the blog post as well.

There is already a "diff" at the top of the README so it doesn't make much difference if it is one sentence or 10 paragraphs. Deleting it consists of highlighe/delete/commit either way.

Arguably making it bigger reduces the likelihood of you accidentally leaving it during the merge.
